services:
  greetings-app-dev:
    container_name: greetings-app-dev
    # The image is pussed to my personal Docker Repo
    image: 'mmatovski/python-greetings-app:latest'
    ports:
      - "7001:3000"
  greetings-app-stg:
    container_name: greetings-app-stg
    image: 'mmatovski/python-greetings-app:latest'
    ports:
      - "7002:3000"
  greetings-app-prd:
    container_name: greetings-app-prd
    image: 'mmatovski/python-greetings-app:latest'
    ports:
      - "7003:3000"
